language: python
python:
  - '3.7'

before_install:
  - export PYTHONPATH=$PYTHONPATH:$PWD

before_script:
  - pwd
  - ls -la purbeurre

# safelist
branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - pytest purbeurre/
